name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Greeting
        run: echo "Hello Github Actions"
      - name: Print GoodBye
        run : echo "Good Bye Github Actions"
 
