name: First Workflow
on: push
jobs:
  test-cases:
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Greeting
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
